### ISSUE TITLE
Suspicious directory in files

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/conda-moose#53]
For example, https://github.com/idaholab/conda-moose/blob/devel/recipes/moose-mpich/info/has_prefix contains `/opt` folder.  If you
```
grep -r anaconda1anaconda2anaconda3 .
```
you will find more.

**Comment by milljm** [comment]
Invalid ticket. This is how it is supposed to be done: https://docs.conda.io/projects/conda-build/en/latest/resources/package-spec.html#info-has-prefix

**Comment by YaqiWang** [comment]
Looks like that is just a place holder to be replaced by real folders. But in some of lib files, this dummy place holder is still showing up. I noticed this because I tried to link the gperftools library and the linker reported back an error saying directory was not found. I have to admit that I do not know conda much though.

**Comment by milljm** [comment]
info/has_prefix, basically instructs the installer to replace any literal occurrence of `/opt/anaconda1anaconda2anaconda3` it finds, with your final installation path.

You're basically looking at a template operation, and how Conda decided to do it. Its pretty convoluted I'll admit.

**Comment by milljm** [comment]
My point being, if you are still seeing /opt/anaconda1anaconda2anaconda3, we need to add _that_ file to info/has_prefix, so it gets replaced. Are these files I control (are they moose- prefixed)?
